# 开启复制模式的 Vim 按键映射
setw -g mode-keys vi

# 像 Vim 一样进行复制选择
# 进入复制模式依然是 Ctrl+b + [
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# 使用 h, j, k, l 切换面板 (前缀 Ctrl+b + h/j/k/l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 快捷重载配置 (Ctrl+b + r)
bind r source-file ~/.tmux.conf \; display "Tmux config reloaded!"

# 开启鼠标支持，方便偶尔用鼠标点选面板或滚动历史
set -g mouse on

# 开启 OSC 52 剪贴板支持（现代终端的跨平台首选）
set -s set-clipboard on

# 关闭视觉响铃
set -g visual-bell off
set -g visual-silence off

# ------- tmux plugins via tpm -------
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin "arcticicestudio/nord-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

