# BEGIN_KITTY_THEME
# Gruvbox Material Dark Soft
include current-theme.conf
# END_KITTY_THEME

background_opacity 0.92
dynamic_background_opacity yes

font_family Meslo LG S NF Regular
font_size 18.0

# enter tmux session `main` by default
# shell tmux new-session -A -s main
shell bash .config/kitty/.tmux-kitty.sh
